export interface DropEvent{
    event_id: string,
    event_name: string,
    sport_type: string,
    location_name: string,
    city: string,
    date: string,
    start_time: string,
    end_time: string,
    max_players: string,
    current_players: string,
    organizer_name: string,
    organizer_ui: string,
    latitude: string,
    longitude: string,
}
